---

# vim-airline
- repo: vim-airline/vim-airline-themes
- repo: vim-airline/vim-airline
  hook_add: |
    let g:airline_theme = 'powerlineish'
    let g:airline#extensions#branch#enabled = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'default'
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tagbar#enabled = 1
    let g:airline_skip_empty_sections = 1
